# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=16)),
                ('pool_one', models.CharField(max_length=100)),
                ('pool_two', models.CharField(max_length=100)),
                ('pool_three', models.CharField(max_length=100)),
                ('hash_rate', models.FloatField()),
            ],
        ),
    ]
