# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20171214_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='type',
            field=models.CharField(choices=[('antd3', 'Antminer D3'), ('antl3', 'Antminer L3')], default='antd3', max_length=20),
        ),
    ]
