# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_miner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='password',
            field=models.CharField(default='root', max_length=20),
        ),
        migrations.AddField(
            model_name='miner',
            name='username',
            field=models.CharField(default='root', max_length=20),
        ),
        migrations.AlterField(
            model_name='miner',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
