# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20171214_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='chain_1_temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miner',
            name='chain_2_temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miner',
            name='chain_3_temp',
            field=models.IntegerField(default=0),
        ),
    ]
