# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-23 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20171216_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='uptime',
            field=models.CharField(default='XX:XX', max_length=20),
        ),
    ]
