# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-24 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20171223_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='pool_one_password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='miner',
            name='pool_one_worker',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='miner',
            name='pool_three_password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='miner',
            name='pool_three_worker',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='miner',
            name='pool_two_password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='miner',
            name='pool_two_worker',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='miner',
            name='pool_one',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='miner',
            name='pool_three',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='miner',
            name='pool_two',
            field=models.CharField(default='', max_length=100),
        ),
    ]
