# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-24 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20171224_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='bitmain_freq',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='miner',
            name='bitmain_vil',
            field=models.CharField(default='true', max_length=10),
        ),
    ]
