# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20171224_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='sshpassword',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
